name: Android CI

on:
  push:
    branches: [ "main", "dev", "alpha", "beta", "prod" ]
  pull_request:
    branches: [ "main", "dev", "alpha", "beta", "prod" ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Determine COUNTRY based on branch
        id: set-country
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "alpha" ]]; then
            echo "COUNTRY=KK" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "beta" ]]; then
            echo "COUNTRY=KY" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "prod" ]]; then
            echo "COUNTRY=PROD" >> $GITHUB_ENV
          else
            echo "COUNTRY=KK" >> $GITHUB_ENV  # default
          fi
          echo "Branch: $BRANCH_NAME"
          echo "Set COUNTRY=$COUNTRY"

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Print selected COUNTRY
        run: echo "Selected COUNTRY is $COUNTRY"

      - name: (Optional) Load COUNTRY from gradle.properties
        run: |
          if grep -q "COUNTRY=" gradle.properties; then
            COUNTRY_FROM_FILE=$(grep "COUNTRY=" gradle.properties | cut -d'=' -f2)
            echo "Overriding COUNTRY from gradle.properties: $COUNTRY_FROM_FILE"
            echo "COUNTRY=$COUNTRY_FROM_FILE" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: ./gradlew test

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
